#! /bin/bash

PACKAGES="
bootstrap
jQuery
Modernizr
Newtonsoft.Json
EntityFramework
jQuery.Validation
Microsoft.Net.Compilers
Respond
Microsoft.AspNet.Mvc
Microsoft.AspNet.Razor
AutoMapper
NUnit
Selenium.WebDriver
Moq
Dapper
Selenium.Support
RestSharp
Google.Protobuf
Microsoft.CodeAnalysis.Common
Microsoft.CodeAnalysis.CSharp
Angular.UI.Bootstrap
Autofac
xunit
NLog
Microsoft.Owin
Microsoft.Owin.Host.SystemWeb
Microsoft.Owin.Security
MahApps.Metro
Nancy
Microsoft.Owin.Security.Cookies
Microsoft.Owin.Security.OAuth
Ninject
underscore.js
Microsoft.Owin.Security.Google
Microsoft.Owin.Security.Facebook
Microsoft.Owin.Security.MicrosoftAccount
Microsoft.Owin.Security.Twitter
xunit.abstractions
Microsoft.CodeAnalysis.Workspaces.Common
Microsoft.CodeAnalysis.CSharp.Workspaces
xunit.core
xunit.assert
xunit.extensibility.core
Antlr
toastr
xunit.runner.visualstudio
xunit.extensibility.execution
Angular.UI.UI-Router
Microsoft.CodeAnalysis.VisualBasic
Microsoft.CodeAnalysis.VisualBasic.Workspaces
Fody
Castle.Core
react.js
Microsoft.CodeAnalysis
Backbone.js
FluentValidation
ServiceStack.Common
SharpZipLib
Unity
lodash
MaterialDesignColors
log4net
Bootstrap.Datepicker
MaterialDesignThemes
mongocsharpdriver
Grpc.Core
Q
StackExchange.Redis
ServiceStack
Microsoft.Rest.ClientRuntime
Swashbuckle.Core
FontAwesome.less
FSharp.Core
Microsoft.Azure.KeyVault.Core
NHibernate
xunit.extensions
Grpc.Tools
animate.css
ServiceStack.Interfaces
protobuf-net
Swashbuckle
normalize.css
Serilog
xunit.runner.console
Grpc
Google.Protobuf.Tools
CsvHelper
FluentNHibernate
Twitter.Typeahead
Prism.Core
sqlite-net-pcl
Cake
Bootstrap.v3.Datetimepicker.CSS
reactiveui-core
Castle.Windsor
Selenium.RC
AutoFixture
MvvmCross
Extended.Wpf.Toolkit
Npgsql
MathNet.Numerics
RazorEngine
xunit.runners
Bootstrap.v3.Datetimepicker
Akka
EPPlus
CommandLineParser
Grpc.Auth
WindowsAzure.Storage
System.IdentityModel.Tokens.Jwt
Topshelf
CefSharp.Common
MiniProfiler
DocumentFormat.OpenXml
ServiceStack.Text
ServiceStack.Client
Costura.Fody
Abp
jQuery.FileUpload
jasmine-js
Mono.Cecil
Microsoft.CodeAnalysis.CSharp.Scripting
Spin.js
NAudio
Microsoft.CodeAnalysis.Scripting.Common
Hangfire.Core
Microsoft.Owin.Hosting
MSTest.TestFramework
Octokit
PagedList
Humanizer
structuremap
Common.Logging
Microsoft.Owin.Host.HttpListener
Selenium.WebDriverBackedSelenium
PagedList.Mvc
FAKE
Prism.Wpf
NPOI
ServiceStack.Redis
sqlite-net
MvvmCross.HotTuna.CrossCore
WebActivatorEx
BenchmarkDotNet
Dapper.Contrib
Polly
TopShelf
Elasticsearch.Net
CefSharp.WinForms
AngleSharp
MvvmCross.Platform
CsQuery
MvvmCross.Binding
Microsoft.Owin.Cors
MvvmCross.Core
Mono.Posix
jquery-globalize
Microsoft.Orleans.Core
Nito.AsyncEx
MvvmCross.HotTuna.MvvmCrossLibraries
Microsoft.VisualStudio.LanguageServices
Microsoft.CodeAnalysis.Analyzers
StyleCop.Analyzers
StackExchange.Redis.StrongName
LiteDB
Abp.Web
FluentMigrator
Abp.Web.Api
Google.Apis
Redis-64
Abp.Web.Mvc
FluentValidation.MVC5
NEST
Google.Apis.Core
NUnit3TestAdapter
MaterialDesignThemes.MahApps
LibGit2Sharp
SimpleInjector
jQuery.Templates
bootstrap-select
MvvmCross.HotTuna.StarterPack
Microsoft.Bot.Builder.History
TwitterBootstrap
Prism.Unity
Owin
CefSharp.Wpf
Google.Apis.Auth
ModernUI.WPF
Common.Logging.Core
Plugin.CurrentActivity
LevelDB-vc120
Angular-UI-Router
CommonServiceLocator
Humanizer.Core
Xamarin.Android.Support.v4
Splat
Prism.Forms
squirrel.windows
PropertyChanged.Fody
Microsoft.Rest.ClientRuntime.Azure
NuGet.CommandLine
ionic
chosen
Microsoft.Orleans.OrleansRuntime
Machine.Specifications
LiveCharts
angular-file-upload
psake
Prism.Unity.Forms
Facebook
Knockout.Validation
AWSSDK.Core
BenchmarkDotNet.Core
ServiceStack.Server
BenchmarkDotNet.Toolchains.Roslyn
Microsoft.CodeAnalysis.Scripting
Microsoft.Orleans.OrleansProviders
Swashbuckle.AspNetCore
WebSocketSharp
Discord.Net
Microsoft.CodeAnalysis.CSharp.Features
ServiceStack.OrmLite.SqlServer
jasmine
chosen.jquery
JQuery_File_Upload_Plugin
Microsoft.Owin.Diagnostics
MSBuildTasks
Xamarin.Android.Support.v7.AppCompat
Microsoft.CodeAnalysis.Compilers
IdentityServer3
MailKit
Xamarin.Android.Support.Design
MassTransit
marked
MediatR
Unity.Interception
Edge.js
Akka.Remote
Microsoft.DiaSymReader.Native
Microsoft.CodeAnalysis.EditorFeatures.Text
StyleCop.MSBuild
Xamarin.Android.Support.Animated.Vector.Drawable
NServiceBus
Xamarin.Android.Support.v7.CardView
YamlDotNet
ExcelDataReader
Microsoft.Orleans.OrleansHost
Microsoft.Owin.Security.Jwt
Microsoft.NETCore.UniversalWindowsPlatform
Xamarin.Android.Support.v7.MediaRouter
ClosedXML
Microsoft.Orleans.OrleansCodeGenerator
Senparc.Weixin
cpprestsdk
Xamarin.Android.Support.v7.RecyclerView
DotNetZip
Microsoft.IdentityModel.Logging
Microsoft.IdentityModel.Tokens
Microsoft.Orleans.Server
AutoFixture.AutoMoq
dotless
Xamarin.Android.Support.Vector.Drawable
Microsoft.Owin.SelfHost
Senparc.Weixin.MP
Sendgrid
FSharp.Data
Topshelf.Log4Net
Microsoft.Owin.Host.SystemWeb.zh-Hans
NodaTime
jQuery.Form
Microsoft.Orleans.CounterControl
Cake.Core
Microsoft.Owin.zh-Hans
Microsoft.Owin.Security.zh-Hans
akavache
ServiceStack.Mvc
Microsoft.Azure.Common.Dependencies
GitVersionTask
DotNetty.Buffers-signed
FsCheck
angular-ui-grid
Microsoft.Owin.FileSystems
xunit.runner.msbuild
Microsoft.Azure.Common
Discord.Net.Commands
Microsoft.Owin.StaticFiles
Senparc.Weixin.Cache.Redis.RedLock
Jil
Microsoft.Orleans.OrleansCodeGenerator.Build
Microsoft.Owin.Security.Facebook.zh-Hans
akavache.core
Microsoft.Owin.Security.Google.zh-Hans
Stateless
Microsoft.Owin.Security.MicrosoftAccount.zh-Hans
angular-loading-bar
Microsoft.Owin.Security.Twitter.zh-Hans
Swagger.Net.UI
EntityFramework.Extended
akavache.sqlite3
cpprestsdk.v140.windesktop.msvcstl.dyn.rt-dyn
ServiceStack.Api.Swagger
MassTransit.RabbitMQ
rangoric.three.js
Flurl
Microsoft.Owin.Security.OpenIdConnect
ZXing.Net
MvvmCross.Droid.Support.V7.AppCompat
Microsoft.CodeAnalysis.Features
AutoFixture.Xunit
ServiceStack.OrmLite
Akka.TestKit
MvvmCross.HotTuna.Plugin.File
Microsoft.Bot.Builder
FluentMigrator.Runner
AWSSDK.S3
MvvmCross.StarterPack
Humanizer.Core.af
refit
modernhttpclient
Slick
AngularJsSeed
Humanizer.Core.ar
Humanizer.Core.bg
Microsoft.Orleans.Client
MaterialSkin
MathNet.Numerics.FSharp
NetMQ
ServiceStack.Common.Signed
Microsoft.Diagnostics.Tracing.TraceEvent
SkiaSharp
SweetAlert.Base
Humanizer.Core.cs
Humanizer.Core.bn-BD
FluentValidation.WebApi
Humanizer.Core.de
Humanizer.Core.uk
Humanizer.Core.es
Simple.Data.Core
xunit.runner.utility
Humanizer.Core.fa
Humanizer.Core.el
Humanizer.Core.da
grpc.native.csharp_ext
Humanizer.Core.fi-FI
Humanizer.Core.fr-BE
Humanizer.Core.fr
Humanizer.Core.hr
Humanizer.Core.he
cpprestsdk.v120.windesktop.msvcstl.dyn.rt-dyn
Humanizer.Core.ru
Humanizer.Core.hu
Humanizer.Core.pt
Humanizer.Core.it
Humanizer.Core.ja
Humanizer.Core.pl
Humanizer.Core.id
Humanizer.Core.nb
Humanizer.Core.nl
Humanizer.Core.nb-NO
Humanizer.Core.sv
MvvmCross.Droid.Support.Fragment
FodyCecil
Twitter.Bootstrap.Sass
Humanizer.Core.ro
Humanizer.Core.sl
Humanizer.Core.sr
Humanizer.Core.sr-Latn
Humanizer.Core.sk
Microsoft.Owin.es
MvvmCross.Droid.Support.Core.UI
PushSharp
Humanizer.Core.uz-Latn-UZ
Humanizer.Core.tr
Humanizer.Core.uz-Cyrl-UZ
Humanizer.Core.zh-CN
Harvest.Chosen
Microsoft.Owin.Testing
Microsoft.Owin.Host.SystemWeb.es
grpc.native.csharp
SQLitePCLRaw.core
Microsoft.Owin.Security.es
Humanizer.Core.vi
Humanizer.Core.zh-Hant
Humanizer.Core.zh-Hans
Thrift
Simple.Data.Ado
Microsoft.Owin.Security.Facebook.es
MvvmCross.HotTuna.Plugin.Messenger
Microsoft.Owin.Security.Google.es
foundation-sites
Microsoft.Owin.Security.MicrosoftAccount.es
jQuery.InputMask
Microsoft.Owin.Security.Twitter.es
ng-grid
MvvmCross.Plugin.Json
SQLitePCLRaw.bundle_green
Twilio
MvvmCross.HotTuna.Plugin.DownloadCache
IdentityServer4
Microsoft.WindowsAzure.Common
Eto.Forms
CefSharp.OffScreen
ReportGenerator
XLabs.IoC
MvvmCross.HotTuna.Plugin.Json
Microsoft.WindowsAzure.Common.Dependencies
JetBrains.Mono.Posix
FSharp.Compiler.Tools
DotNetty.Buffers
WindowsAzure.MobileServices
PInvoke.Windows.Core
PInvoke.Kernel32
Facebook.Yoga
MvvmCross.Droid.Support.V7.RecyclerView
Discord.Net.WebSocket
System.Linq.Dynamic
PetaPoco
DotNetty.Codecs
Microsoft.Orleans.OrleansAzureUtils
Discord.Net.Core
JWT
EasyNetQ
MvvmCross.Droid.Shared
SQLite.Net-PCL
PInvoke.BCrypt
DotNetty.Common
Sprache
PInvoke.NCrypt
DotNetty.Transport
Akka.Cluster
Discord.Net.Rest
DotNetty.Handlers
Xamarin.Android.Support.Compat
ECharts
EnyimMemcached
Topshelf.NLog
FluentMigrator.Tools
lodash.underscore
XLabs.Core
Microsoft.Orleans.Templates.Grains
Xamarin.Android.Support.Core.UI
Angular.UI.Utils
Akka.Persistence
DotNetty.Transport-signed
DotNetty.Codecs-signed
DotNetty.Common-signed
XLabs.Serialization
Microsoft.Orleans.Templates.Interfaces
FSharp.Formatting
Microsoft.Owin.Security.ActiveDirectory
Xamarin.FFImageLoading
Xamarin.Android.Support.Core.Utils
XLabs.Platform
Xamarin.Android.Support.Fragment
Xamarin.Android.Support.Media.Compat
DotNetty.Codecs.Mqtt-signed
DotNetty.Handlers-signed
BenchmarkDotNet.Diagnostics.Windows
Acr.UserDialogs
Microsoft.IO.RecyclableMemoryStream
Microsoft.Azure.Search
Microsoft.VisualStudio.Threading
Microsoft.WindowsAzure.Management.Storage
XLabs.Forms
Antlr4.Runtime.Standard
Flurl.Http
LibLog
cpprestsdk.v120.winapp.msvcstl.dyn.rt-dyn
cpprestsdk.v140.winapp.msvcstl.dyn.rt-dyn
cpprestsdk.v120.winphone.msvcstl.dyn.rt-dyn
cpprestsdk.v120.winxp.msvcstl.dyn.rt-dyn
cpprestsdk.v120.winphonesl.msvcstl.dyn.rt-dyn
localForage
Jint
Discord.Net.Rpc
ICSharpCode.NRefactory
Telegram.Bot
ServiceStack.Host.Mvc
ServiceStack.Client.Signed
Microsoft.Owin.Host.SystemWeb.ru
Avalonia
Microsoft.Owin.ru
MvvmCross.Plugin.Messenger
Xamarin.Android.Support.Annotations
MimeKit
Discord.Net.Webhook
ServiceStack.Signed
Dapper.StrongName
Microsoft.ProjectOxford.Face
Microsoft.Orleans.OrleansTelemetryConsumers.Counters
Microsoft.Owin.Security.ru
FSharp.Compiler.Service
libsodium_vc120
Microsoft.WindowsAzure.Management.Compute
Microsoft.Rest.ClientRuntime.Azure.Authentication
Microsoft.Owin.Host.SystemWeb.zh-Hant
ICSharpCode.Decompiler
Microsoft.Azure.KeyVault
SQLitePCLRaw.provider.e_sqlite3.android
SQLitePCLRaw.lib.e_sqlite3.android
Xamarin.FFImageLoading.Forms
MvvmCross.HotTuna.Plugin.Visibility
ZeroClipboard
FSharpVSPowerTools.Core
SteamKit2
Microsoft.Owin.Security.Facebook.zh-Hant
Microsoft.Owin.Security.zh-Hant
Microsoft.Owin.Security.MicrosoftAccount.zh-Hant
AutoFixture.Xunit2
Microsoft.Owin.zh-Hant
Microsoft.Owin.Security.Google.zh-Hant
Microsoft.Owin.Security.Facebook.ru
Microsoft.WindowsAzure.Management.Scheduler
Microsoft.Owin.Security.Google.ru
taglib
Microsoft.Owin.Security.Twitter.zh-Hant
Microsoft.Owin.Security.MicrosoftAccount.ru
showdown
MvvmCross.Plugin.File
Pomelo.EntityFrameworkCore.MySql
Microsoft.Azure.Management.Resources
Microsoft.Owin.Security.Twitter.ru
Refit
Microsoft.ChakraCore
Akka.TestKit.Xunit2
PCLStorage
RequireJS.Text
Xam.Plugin.Media
System.IO.Abstractions
Microsoft.WindowsAzure.Management
SkiaSharp.Views
Fleck
Unity.Container
DockPanelSuite
bootstrap-sass
Tesseract
Microsoft.WindowsAzure.Management.WebSites
MsgPack.Cli
Npgsql.EntityFramework
Akka.FSharp
Microsoft.IdentityModel.Protocols.OpenIdConnect
Redis-32
AjaxControlToolkit
AutoFixture.AutoNSubstitute
MySqlConnector
libzmq_vc120
Xamarin.Android.Support.Transition
MahApps.Metro.Resources.Standalone
es5-shim
Microsoft.IdentityModel.Protocols
Dapper.Rainbow
angular-local-storage
HubSpot.Tether
SkiaSharp.Views.Forms
FluentValidation-Signed
Senparc.Weixin.MP.MVC
OpenCvSharp3-AnyCPU
CommonMark.NET
DocX
Microsoft.Orleans.TestingHost
bootstrap-fileinput
linq2db
Thinktecture.IdentityServer3
Microsoft.WindowsAzure.Management.Sql
selectize
Akka.DI.Core
Cake.Testing
Humanizer.Core.lv
FsUnit
OfficeUIFabric
Xam.Plugin.Connectivity
Bogus
SQLite.Net.Core-PCL
Xam.Plugins.Settings
TestStack.White
StyleCop
Polly-Signed
ServiceStack.Logging.NLog
ServiceStack.Host.AspNet
IdentityModel
MvvmCross.Droid.Support.V4
ModalStart
Stripe.net
Xamarin.Android.Support.v7.Palette
WinJS
GitVersion.CommandLine
NBitcoin
DapperExtensions
Microsoft.CodeAnalysis.VisualBasic.Features
Microsoft.WindowsAzure.Management.Network
ILMerge
SQLitePCLRaw.provider.sqlite3.ios_unified
Simple.Data.SqlServer
Markdig
JetBrains.MahApps.Metro
Restangular
Bond.Runtime.CSharp
OpenCover
Cake.Common
Microsoft.WindowsAzure.Management.MediaServices
Vue.js.Developers.Version
Google.Apis.Drive.v2
SharpCompress
MvvmCross.HotTuna.Plugin.PictureChooser
MvvmCross.Droid.Support.Design
ClientDependency
Sigil
Google.Apis.Calendar.v3
ApprovalTests
GraphQL
DotNetty.Codecs.Mqtt
OpenCvSharp-AnyCPU
AWSSDK.DynamoDBv2
SixLabors.ImageSharp
Nito.AsyncEx.Tasks
MediaBrowser.Common
Eto.Platform.Gtk
chocolatey
ServiceStack.Caching.Memcached
ServiceStack.Authentication.OpenId
LinqToExcel
ILRepack
Eto.Platform.Wpf
MvvmCross.HotTuna.Binding
MvvmCross.Plugin.Visibility
AutoRest
Microsoft.Bot.Connector
FluentScheduler
jquery.noty
Iesi.Collections
gong-wpf-dragdrop
Nito.AsyncEx.Context
html5-shiv
FluentValidation.Mvc5
Microsoft.Bot.Builder.Calling
PCLCrypto
Xamarin.GooglePlayServices.Base
MvvmCross.Plugin.DownloadCache
sharpcompress
FsCheck.Xunit
SourceLink.Fake
Bond.Core.CSharp
axios.js
Tether.New
MvvmCross.Droid.Support.Core.Utils
rapidjson
Bond.CSharp
Cake.CoreCLR
Yarnpkg.Yarn
TinyIoC
Xamarin.GooglePlayServices.Basement
ZXing.Net.Mobile
googletest
MvcSiteMapProvider.Web
TweetinviAPI
MvvmCross.HotTuna.Plugin.Location
Should
EasyHttp
knockoutjs
PDFsharp
Eto.Platform.Windows
Microsoft.WindowsAzure.Management.Monitoring
Microsoft.Owin.fr
MvvmCross.HotTuna.Tests
BabylonJS
Microsoft.Owin.Host.SystemWeb.fr
angular-strap
docfx.msbuild
Azure.Batch
EWSoftware.SHFB
AutoFixture.Idioms
ImpromptuInterface
MassTransit.Log4Net
Microsoft.Owin.Security.fr
Microsoft.Owin.Security.Facebook.fr
Examine
Topshelf.Serilog
Microsoft.Owin.Security.Google.fr
Backbone.Marionette
Avalonia.Desktop
Microsoft.Owin.Security.MicrosoftAccount.fr
Microsoft.Owin.Security.Twitter.fr
Microsoft.Gsl
Angular.Strap
Microsoft.Owin.Security.WsFederation
Elmah.MVC
ServiceStack.OrmLite.Sqlite.Mono
Effort.EF6
Xamarin.FFImageLoading.Transformations
Plugin.Permissions
JsonFx
introjs
Microsoft.WindowsAzure.Management.Libraries
LinqKit
AttributeRouting.Core
FluentValidation.AspNetCore
SQLitePCL.raw_basic
Fluent.Ribbon
MvcSiteMapProvider.MVC5.Core
Microsoft.Azure.Management.Batch
CSCore
SquishIt
ini-parser
Microsoft.WindowsAzure.Management.ServiceBus
MvcSiteMapProvider.MVC5
Sprache.JetBrains
Strathweb.CacheOutput.WebApi2
ServiceStack.Logging.Log4Net
ServiceStack.Caching.Azure
SlickGrid
ApprovalUtilities
System.IO.Abstractions.TestingHelpers
Antlr4.Runtime
Microsoft.Hadoop.Avro
Microsoft.Hadoop.Client
Akka.Persistence.Sql.Common
Eto.Platform.Mac
Microsoft.ApplicationInsights.AspNetCore
Antlr4
Microsoft.Azure.KeyVault.WebKey
Eto.Platform.Gtk3
WebSocketSharp-NonPreRelease
MSBuild.Extension.Pack
PetaPoco.Core
Xam.Plugin.Geolocator
fullcalendar
Abot
NBuilder
Microsoft.Azure.Mobile.Client
WindowsAzure.MobileServices.Backend
FullPageJS
Neo
MahApps.Metro.IconPacks
WindowsAzure.MobileServices.Backend.Tables
Chutzpah
MessagePack
CoffeeScript
SocketIoClientDotNet
Nito.AsyncEx.Coordination
MassTransit.Autofac
WindowsAzure.MobileServices.Backend.Entity
ratchet
Realm.Database
Microsoft.WindowsAzure.Management.HDInsight
Owin.Security.Providers
SQLite.Net.Async-PCL
AttributeRouting.Core.Web
Google.Apis.Drive.v3
ServiceStack.Text.Signed
FluentCommandLineParser
Realm
Microsoft.Azure.Graph.RBAC
Microsoft.Azure.Management.DataFactories
ngGrid
x-editable
Common.Logging.Log4Net
linq2db.t4models
angular-google-maps
BrockAllen.MembershipReboot
ExcelDataReader.DataSet
docfx.console
Xamarin.GooglePlayServices.Maps
System.IO.Pipelines
Prism.Autofac.Forms
Handsontable
MvvmCross.Forms
MvvmCross.HotTuna.Touch.Dialog
alertify
ClientDependency-Mvc5
Holder.js
ReactiveProperty
AWSSDK.CognitoIdentity
QRCoder
MaterialSkin.Updated
Akka.Serialization.Hyperion
Nustache
Prism.DryIoc.Forms
Xamarin.TestCloud.Agent
Cassette
NetTopologySuite
ServiceStack.OrmLite.MySql
autorest
MvvmCross.Tests
MvvmCross.HotTuna.Plugin.ResourceLoader
jQuery.Pjax
Catel.Core
Abp.Application
jose-jwt
AWSSDK.SQS
Swashbuckle.AspNetCore.Swagger
MediaBrowser.Server.Core
OwinHost
FsPickler
protobuf.net35
paper-behaviors
paper-ripple
polymer-iron-behaviors
polymer-iron-a11y-keys-behavior
paper-styles
polymer-iron-flex-layout
Microsoft.Azure.Management.StreamAnalytics
jQuery-Timepicker-Addon
Chronic.Signed
EmberJS
Xamarin.Azure.NotificationHubs.Android
MvvmCross.HotTuna.Plugin.MethodBinding
googletest.redist
Microsoft.Bot.Builder.FormFlow.Json
EntityFramework.DynamicFilters
Pester
Microsoft.Azure.Management.KeyVault
Microsoft.Azure.Management.Storage
Fixie
Callisto
ControlzEx
MouseKeyHook
dapper
Dapper.SqlBuilder
Microsoft.Orleans.Core.Abstractions
Microsoft.Owin.ja
Microsoft.Owin.Host.SystemWeb.ja
AttributeRouting
T4MVC
Realm.DataBinding
Discord.Net.Audio
Paket.Core
Xamarin.Auth
Microsoft.Owin.Security.ja
Akka.Serialization.Wire
MvvmCross.Plugin.Color
MetroFramework
MapSuiteDependency-NetTopologySuite
ServiceStack.HttpClient
Bootstrap.Multiselect
DropNet
Rotativa
Prism.Autofac
Jurassic
T4MVCExtensions
librdkafka.redist
NuGet.Core
NPoco
ClientDependency-Mvc
CocosSharp.PCL.Shared
Magick.NET-Q16-AnyCPU
CacheCow.Common
HtmlTags
YoutubeExtractor
AutoFixture.NUnit3
MetroFramework.RunTime
Microsoft.Azure.Management.Automation
Deedle
Hammer.js
YamlDotNet.Signed
WindowsAPICodePack-Core
ZXing.Net.Mobile.Forms
MonoGame.Extended
Discord.Net.Modules
Microsoft.Azure.Gallery
MetroFramework.Design
Bootstrap.DateTimePicker
angular-moment
MetroFramework.Fonts
JSZip
axios
ServiceStack.Authentication.OAuth2
ServiceStack.MsgPack
ServiceStack.OrmLite.PostgreSQL
FakeSign
Microsoft.Azure.Management.ResourceManager
angular-ui-select
MvvmCross.Plugin.ResourceLoader
MvvmCross.HotTuna.Plugin.JsonLocalisation
Common.Logging.Log4Net1213
WebSocketSharpFork
NuGet.Versioning
angular-file-upload-module
Akka.Cluster.Tools
Akka.Persistence.TestKit
ServiceStack.Redis.Signed
Twilio.TwiML
MSBuild
JavaScriptEngineSwitcher.Core
EWSoftware.SHFB.NETFramework
Microsoft.Azure.Services.AppAuthentication
Swashbuckle.AspNetCore.SwaggerUI
RelaxNG
Eto.Platform.Mac.Template
Xamarin.GooglePlayServices.Tasks
Microsoft.CodeCoverage
SQLitePCLRaw.lib.e_sqlite3.osx
Cassette.Views
Microsoft.WindowsAzure.Management.TrafficManager
MvvmCross.HotTuna.Plugin.Color
MvvmCross.HotTuna.Droid.FullFragging
SixLabors.ImageSharp.Drawing
AutoFixture.NUnit2
SQLitePCLRaw.lib.e_sqlite3.v110_xp
SQLitePCLRaw.lib.e_sqlite3.linux
WriteableBitmapEx
Microsoft.TestPlatform.TestHost
Fake.Core.String
TensorFlowSharp
Common.Logging.Log4Net1211
Docker.DotNet
Akka.Streams
Microsoft.Owin.Security.Google.ja
Microsoft.Owin.Security.Twitter.ja
Microsoft.Azure.Management.Authorization
RazorGenerator.Mvc
SQLitePCLRaw.provider.e_sqlite3.net45
ServiceStack.RabbitMq
ServiceStack.Logging.Elmah
Metrics.NET
Senparc.Weixin.Cache.Redis
Fake.IO.FileSystem
Microsoft.Owin.Security.MicrosoftAccount.ja
Microsoft.Owin.Security.Facebook.ja
ngTable
Xamarin.Forms.Labs
Microsoft.TestPlatform.ObjectModel
AutoFixture.AutoFakeItEasy
Microsoft.PowerShell.SDK
Microsoft.WSMan.Management
FontAwesome.WPF
Rg.Plugins.Popup
Eto.Serialization.Xaml
Fake.Core.Process
PayPal
SQLitePCL.raw
HtmlSanitizer
SQLite.Net.Platform.XamarinAndroid
Swashbuckle.AspNetCore.SwaggerGen
VideoJS
VideoJs
MvvmCross.Forms.Presenter
FodyHelpers
Serenity.Data
Serenity.Core
Fake.Core.Trace
Fake.Core.Context
Fake.DotNet.Cli
Fake.Core.Environment
almond
xunit.assert.source
semver
underscore-string
LanguageExt.Core
inputMask
Fake.Core.Target
Microsoft.Orleans.EventSourcing
Nuget.Core
Serenity.Services
Serenity.Web
Serenity.Data.Entity
NuGet.VisualStudio
AWSSDK.SecurityToken
AWSSDK.Route53
MvcMailer
Elmah.Mvc
CoffeeScriptCompiler
Fake.Core.FakeVar
Gherkin
MvvmCross.HotTuna.Plugin.Network
MvvmCross.HotTuna.Plugin.Sqlite
MvvmCross.Plugin.JsonLocalization
apache-thrift-netcore
NuGet.Packaging
harvesthq.chosen
Perspex
Mono.Posix.NETStandard
CacheCow.Server
Fake.Core.CommandLineParsing
Serenity.CodeGenerator
Refractored.MvvmHelpers
metisMenu
Octokit.Reactive
pace.js
WindowsAPICodePack-Shell
Microsoft.Azure.Management.Network
Magnum
MassTransit.Automatonymous
jasminejs
FsUnit.xUnit
Twilio.Mvc
Pandoc.Windows
linqtotwitter
SQLite.Net.Platform.XamarinIOS
Google.Apis.Gmail.v1
Microsoft.Orleans.OrleansSqlUtils
polymer-core-component-page
polymer-cyclic
polymer-platform
polymer-iron-icons
polymer-iron-iconset-svg
polymer-iron-icon
polymer-iron-meta
Microsoft.Owin.pt-br
Microsoft.Owin.Host.SystemWeb.pt-br
BrockAllen.MembershipReboot.Ef
"

for P in $PACKAGES ; do
    dotnet add package "$P"
done



